apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: mongodb-pod
      labels:
        type: backend
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-volume
      # TODO Create volume from pvc claim mongo-pvc1-test