apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: low-resource-app
  template:
    metadata:
      labels:
        app: low-resource-app
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
