apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-replicaset
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: technoavengers/flask-app:v1
        ports:
        - containerPort: 5000
